language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.1.3
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
# command to run tests
script:
  - python manage.py makemigrations
  - coverage run --source="." manage.py test billjobs
after_success:
  - coveralls
